# Labeler configuration for Repo-Scout

frontend:
  - 'src/**/*'
  - 'public/**/*'

dependencies:
  - 'package.json'
  - 'package-lock.json'
  - 'bun.lockb'

documentation:
  - '**/*.md'
  - 'README.md'
  - 'docs/**/*'

config:
  - '.github/**/*'
  - 'tsconfig.json'
  - 'vite.config.*'
  - 'tailwind.config.*'
  - 'postcss.config.*'
  - '.eslintrc*'
  - '.env*'

tests:
  - '**/*.test.*'
  - '**/__tests__/**/*'

ci:
  - '.github/workflows/*'s